### ISSUE TITLE
file summary

### ISSUE THREAD

**Issue by fommil** [hvesalai/scala-mode2#77]
I'm not sure if this is best implemented in ENSIME or `scala-mode2`: https://github.com/ensime/ensime-server/issues/471

It may well be done with regexes instead of having to understand the AST.

What do you think?

**Comment by IvanMalison** [comment]
This can be closed now.

**Comment by fommil** [comment]
@IvanMalison I'm actually confused by the recent PR... has the scala-outline-popup now been merged into scala-mode2 or is it a separate functionality? How can I try out the new feature?

**Comment by IvanMalison** [comment]
It's not using scala-outline-popup. The functionality was implemeted using imenu which can be accessed with M-x imenu. This should open a completing read of the available symbols in the completion system that you use. With helm it will look something like this
![imenu_screenshot](https://cloud.githubusercontent.com/assets/1246619/5745648/2ac07c6e-9bdf-11e4-9bf1-3bc9624dc3da.png)
