### ISSUE TITLE
Indentation when using a parenthesis

### ISSUE THREAD

**Issue by nloyola** [hvesalai/scala-mode2#86]
I get bad indentation if I use a parenthesis to start a line. For example:

```scala
val json: JsValue = Json.parse("""{ "name": "test", "email": "test@test.com" }""")

(json \ "name").as[String] mustBe ("test")
  (json \ "email").as[String] mustBe ("test@test.com")
```

The second line starting with parenthesis is indented.

If I omit the blank line I get:

```scala
val json: JsValue = Json.parse("""{ "name": "test", "email": "test@test.com" }""")
  (json \ "name").as[String] mustBe ("test")
  (json \ "email").as[String] mustBe ("test@test.com")
```
Both lines starting with parenthesis are indented.
 
Where in the code can I look to try to fix this?

Thanks

**Comment by hvesalai** [comment]
This is intended, so do _not_ try to fix it. See documentation on run-on lines.
