### ISSUE TITLE
jump over imports when opening files

### ISSUE THREAD

**Issue by fommil** [hvesalai/scala-mode2#90]
it would be pretty useful to jump to the first non-package, non-import line in a scala file when opening.

**Comment by hvesalai** [comment]
Hmm... maybe attach something to the `find-file-hook` hook that will position the file.

**Comment by fommil** [comment]
yup, we might have some regex in ENSIME that finds the right place to put new imports... probably does this.

**Comment by fommil** [comment]
I can probably cook something up from https://github.com/ensime/ensime-emacs/blob/master/ensime-editor.el#L493

**Comment by fommil** [comment]
```
(defun scala-mode:goto-start-of-code ()
  "Go to the start of the real code in the file, going to the first object, class or trait."
  (interactive)
  (let* ((case-fold-search nil))
    (search-forward-regexp "\\(class\\|object\\|trait\\)" nil t)))
```

**Comment by fommil** [comment]
(if anybody actually wrote comments in Scala, perhaps we should jump to those as well)
